"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import axios from "axios";
import { Header } from "../../components/ui/Header";
import { registerUser } from "../../services/user.service";
const messageFrom = (error: unknown) => { const data = axios.isAxiosError(error) ? error.response?.data : undefined; if (data && typeof data === "object") { const details = (data as { errors?: Record<string, string[]>, message?: string }).errors; return details ? Object.values(details).flat().join(" ") : (data as { message?: string }).message || "Unable to create your account."; } return "Unable to connect to the server. Please try again."; };
export default function RegisterPage() {
  const [complete, setComplete] = useState(false); const [code, setCode] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(""); setLoading(true); try { const response = await registerUser({ email: String(form.get("email")).trim(), first_name: String(form.get("firstName")).trim(), last_name: String(form.get("lastName")).trim() }); setCode(response.code); setComplete(true); } catch (requestError) { setError(messageFrom(requestError)); } finally { setLoading(false); } }
  return <main className="site-shell inner-page"><Header /><section className="register-wrap"><span className="design-label">Create your account</span><div className="register-card">{complete ? <div className="register-success"><div className="success-check">✓</div><h1>Registration Done</h1><p>Your account has been created successfully.</p><span>Your Login Code</span><strong>{code}</strong><small>Keep this code for future login.</small><Link href="/checkout" className="primary-button">Go to Checkout <b>→</b></Link></div> : <><form className="registration-form" onSubmit={submit}><div className="form-title-icon">♙</div><h1>Create Your Account</h1><p>Register to receive your 6-digit login code</p>{error && <p className="form-error" role="alert">{error}</p>}<label>Email Address<input name="email" required type="email" placeholder="you@example.com" disabled={loading} /></label><label>First Name<input name="firstName" required placeholder="Enter your first name" disabled={loading} /></label><label>Last Name<input name="lastName" required placeholder="Enter your last name" disabled={loading} /></label><button className="primary-button" type="submit" disabled={loading}>{loading ? "Registering..." : "Register"}</button><span className="form-foot">Already have an account? <Link href="/checkout">Go to Checkout</Link></span></form><aside className="register-art" aria-hidden="true"><div className="mini-browser"><span /><span /><span /><div className="mini-user">●</div></div><div className="plant">♣</div><div className="floating-plus">+</div><div className="art-copy">♢ <span>Your information is safe<br /><small>We never share your data.</small></span></div></aside></>}</div></section></main>;
}
