# Generated by Django 6.1 on 2026-08-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
